card/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('list_student/',views.List_student.as_view(),name='list_student'),
    path('list_employee/',views.List_employee.as_view(),name='list_employee'),
    path('detail/<pk>',views.Detail_student.as_view(),name='detail_student'),
    path('detail_employee/<pk>',views.Detail_employee.as_view(),name='detail_employee'),
    path('new_student/',views.New_student.as_view(),name='new_student'),
    path('new_employee/',views.New_employee.as_view(),name='new_employee'),
    path('update/<pk>',views.Update_student.as_view(),name='update_student'),
    path('update_employee/<pk>',views.Update_employee.as_view(),name='update_employee'),
    path('delete_student/<pk>',views.Delete_student.as_view(),name='delete_student'),
    path('delete_employee/<pk>',views.Delete_employee.as_view(),name='delete_employee'),
    path('print/<pk>', views.GeneratePdf.as_view(),name='print'),
    path('print_employee/<pk>', views.GeneratePdf_employee.as_view(),name='print_employee'),
    path('barcode/<bar_id>', views.barcode,name='barcode'),
    path('add_new/', views.add_new,name='add_new'),
]

id/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('card.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('visitor/',include('visitor.urls'))
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

visitor/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='visitor'
urlpatterns = [
    
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('list/',views.list_view,name='list'),
    path('checkedin_list/',views.checkedin_list,name='checkedin_list'),
    path('check_out/<pk>/',views.check_out,name='check_out'),
    path('detail/<pk>/',views.detail,name='detail'),
    path('print/<pk>/', views.GeneratePdf.as_view(),name='print'),
]

card/models.py
import random,string
from django.db import models
from django.utils import timezone
from django.urls import reverse
from reportlab.lib.units import mm
from reportlab.graphics.barcode import createBarcodeDrawing
from reportlab.graphics.shapes import Drawing, String
from reportlab.graphics.charts.barcharts import HorizontalBarChart
from . import mybarcode
import os


class Card_detail(models.Model):
    roll_no=models.CharField(max_length=256,primary_key=True)
    name=models.CharField(max_length=256)
    father_name=models.CharField(max_length=256)
    dob=models.DateField()
    programme=models.CharField(max_length=256)
    blood_group=models.CharField(max_length=256)
    issued_on=models.DateField()
    valid_upto=models.DateField()
    pic = models.ImageField(upload_to = 'images/',null=True,verbose_name="")

    def __str__(self):
        return self.roll_no
    class Meta:
        ordering = ["roll_no"]

    def get_absolute_url(self):
        mybarcode.MyBarcodeDrawing(self.roll_no).save(formats=['png'],outDir=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'media/barcodes/'),fnRoot=self.roll_no) 
        return reverse('list_student')

ID_LENGTH = 4
def create_unique_id():
    return ''.join(random.choices(string.digits, k=ID_LENGTH))
def id_gen()-> str:
    idd = create_unique_id()
    unique = False
    while not unique:
        if not idd in Employee_Card.objects.filter(e_id=id).values_list('e_id', flat=True):
            unique = True
        else:
            idd = create_unique_id()
    mybarcode.MyBarcodeDrawing(idd).save(formats=['png'],outDir=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'media/barcodes/'),fnRoot=idd)
    return idd



class Employee_Card(models.Model):

    e_id = models.CharField(max_length=ID_LENGTH, primary_key=True, default=id_gen, editable=False)
    name=models.CharField(max_length=256)
    designation=models.CharField(max_length=256)
    dob=models.DateField()
    blood_group=models.CharField(max_length=256)
    pic = models.ImageField(upload_to = 'images/',null=True,verbose_name="")
    valid_upto=models.DateField()
    issued_on=models.DateField(null=True)

    def __str__(self):
        return self.e_id
    # class Meta:
    #     ordering = ["e_id"]

    def get_absolute_url(self):
        return reverse('list_employee')

card/forms.py
from django import forms
import datetime
from .models import Card_detail,Employee_Card


class DateInput(forms.DateInput):
   input_type = 'date'

class Card_detail_form(forms.ModelForm):
   # roll_no = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder':'Roll Number','class':'form-control'}))
   # name=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Name','class':'form-control'}))
   # father_name=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Father\'s Name','class':'form-control'}))
   # dob=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Date of Birth','class':'form-control','id':'datepicker1'}))
   # programme=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Programme','class':'form-control'}))
   # blood_group=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Blood Group','class':'form-control'}))
   # valid_upto=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Valid Upto','class':'form-control','id':'datepicker'}))
   # issued_on=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'issued_on','class':'form-control','id':'datepicker2'}))
   # #pic=forms.CharField(label="",widget=forms.FileInput(attrs={'name':'pic'}))
  
   class Meta():
       model=Card_detail
       fields='__all__'
       widgets={
       'roll_no':forms.TextInput(attrs={'placeholder':'Roll Number','class':'form-control'}),
       'name':forms.TextInput(attrs={'placeholder':'Name','class':'form-control'}),
       'father_name':forms.TextInput(attrs={'placeholder':'Father\'s Name','class':'form-control'}),
       'dob':forms.TextInput(attrs={'placeholder':'Date of Birth','class':'form-control','id':'datepicker1'}),
       'programme':forms.TextInput(attrs={'placeholder':'Programme','class':'form-control'}),
       'blood_group':forms.TextInput(attrs={'placeholder':'Blood Group','class':'form-control'}),
       'valid_upto':forms.TextInput(attrs={'placeholder':'Valid Upto','class':'form-control','id':'datepicker'}),
       'issued_on':forms.TextInput(attrs={'placeholder':'issued_on','class':'form-control','id':'datepicker2'}),
       # 'pic':forms.FileInput(attrs={'name':'pic','paceholder':'Photo','class':'form-control'}),'roll_no':forms.TextInput(attrs={'placeholder':'Roll Number'}),
       # 'name':forms.TextInput(attrs={'placeholder':'Name'}),
       # 'father_name':forms.TextInput(attrs={'placeholder':'Father\'s Name'}),
       # 'dob':DateInput(attrs={'placeholder':'Date of Birth'}),
       # 'programme':forms.TextInput(attrs={'placeholder':'Programme'}),
       # 'blood_group':forms.TextInput(attrs={'placeholder':'Blood Group'}),
       # 'valid_upto':DateInput(attrs={'placeholder':'Valid Upto'}),
       # 'issued_on':DateInput(attrs={'placeholder':'issued_on'}),
       'pic':forms.FileInput(attrs={'name':'pic','paceholder':'Photo','class':'form-control'}),

       }


class Employee_card_form(forms.ModelForm):
  # name=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Name','class':'form-control'}))
  # designation=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Designation','class':'form-control'}))
  # dob=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Date of Birth','class':'form-control','id':'datepicker1'}))
  # blood_group=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Blood Group','class':'form-control'}))
  # # pic=forms.CharField(label="",widget=forms.FileInput(attrs={'name':'pic'}))
  # valid_upto=forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Valid Upto','class':'form-control','id':'datepicker1'}))
  class Meta():
    model=Employee_Card
    fields='__all__'
    widgets={
    'name':forms.TextInput(attrs={'placeholder':'Name','class':'form-control'}),
    'designation':forms.TextInput(attrs={'placeholder':'Designation','class':'form-control'}),
    'dob':forms.TextInput(attrs={'placeholder':'Date of Birth','class':'form-control','id':'datepicker1'}),
    'blood_group':forms.TextInput(attrs={'placeholder':'Blood Group','class':'form-control'}),
    'pic':forms.FileInput(attrs={'name':'pic','class':'form-control','placeholder':'Photo'}),
    'valid_upto':forms.TextInput(attrs={'placeholder':'Valid Upto','class':'form-control','id':'datepicker'}),           
    'issued_on':forms.TextInput(attrs={'placeholder':'Issued on','class':'form-control','id':'datepicker2'}),           
    }

card/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from card import forms,models
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
	return render(request,'card/index.html')

def add_new(request):
	return render(request,'card/add_new.html')

class List_student(LoginRequiredMixin,ListView):
	context_object_name='list'
	model=models.Card_detail
	template_name='card/list.html'

class List_employee(LoginRequiredMixin,ListView):
	context_object_name='list'
	model=models.Employee_Card
	template_name='card/list_employee.html'

class Detail_student(LoginRequiredMixin,DetailView):
	context_object_name='student_detail'
	model=models.Card_detail
	template_name='card/detail.html'

class Detail_employee(LoginRequiredMixin,DetailView):
	context_object_name='employee_detail'
	model=models.Employee_Card
	template_name='card/employee_detail.html'

class New_student(LoginRequiredMixin,CreateView):
	model=models.Card_detail
	template_name='card/new.html'
	form_class=forms.Card_detail_form

class New_employee(LoginRequiredMixin,CreateView):
	model=models.Employee_Card
	template_name='card/new_employee.html'
	form_class=forms.Employee_card_form

class Update_student(LoginRequiredMixin,UpdateView):
	form_class=forms.Card_detail_form
	model=models.Card_detail
	template_name='card/update.html'

class Update_employee(LoginRequiredMixin,UpdateView):
	form_class=forms.Employee_card_form
	model=models.Employee_Card
	template_name='card/update_employee.html'

class Delete_student(LoginRequiredMixin,DeleteView):
	model=models.Card_detail
	template_name='card/delete.html'
	success_url=reverse_lazy('list_student')

class Delete_employee(LoginRequiredMixin,DeleteView):
	model=models.Employee_Card
	template_name='card/delete.html'
	success_url=reverse_lazy('list_employee')

from django.http import HttpResponse
from django.views.generic import View
from utils import render_to_pdf #created in step 4

class GeneratePdf(View):
	def get(self, request, *args, **kwargs):
		primary=self.kwargs['pk']
		student=models.Card_detail.objects.get(pk=primary)
		data={'student':student}
		pdf = render_to_pdf('card/card.html', data)
		return HttpResponse(pdf, content_type='application/pdf')

class GeneratePdf_employee(View):
	def get(self, request, *args, **kwargs):
		primary=self.kwargs['pk']
		employee=models.Employee_Card.objects.get(pk=primary)
		data={'employee':employee}
		pdf = render_to_pdf('card/employee_card.html', data)
		return HttpResponse(pdf, content_type='application/pdf')

import os
from . import mybarcode
def barcode(request,bar_id):
    mybarcode.MyBarcodeDrawing(bar_id).save(formats=['png'],outDir=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'media/barcodes/'),fnRoot=bar_id)
    return HttpResponse('image printed')

templates/card/add_new.html
{%extends 'card/base.html'%}
{%load static%}
{% block active%}
      <li><a href="{%url 'index'%}"><i class="fas fa-home"></i>&ensp; Home</a></li>
      <li><a href="{%url 'list_student'%}"><i class="fas fa-graduation-cap"></i>&ensp; Student</a></li>
      <li><a href="{%url 'list_employee'%}"><i class="fas fa-chalkboard-teacher"></i>&ensp;Faculty</a></li>
      <li class="active"><a href="{%url 'add_new'%}"><i class="fa fa-address-card-o"></i>Register</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle " data-toggle="dropdown" href="#">Visitor
        <span class="caret"></span></a>
        <ul class="dropdown-menu ">
          <li><a href="{%url 'visitor:register'%}">Add new</a></li>
          <li><a href="{%url 'visitor:checkedin_list'%}">Checked In</a></li>
          <li><a href="{%url 'visitor:list'%}">Checked Out</a></li>
        </ul>
      </li>
    </ul>
  {% endblock active %}
{%block content%}
<head>
  <title>Register</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <style>
      body{
	background-color: #FFF;   
}

.vertical-offset-100{
	padding-top:100px;
}

.nav .open>a, .nav .open>a:focus, .nav .open>a:hover {
	background-color: #2F2F2F;
}

.grow {
	transition: all .2s ease-in-out;
}
.grow:hover {
	transform: scale(1.1);
}
.imgWrap {
	position: relative;
	height: 130px;
	width: 130px;
}

.imgDescription {
	position: absolute;
	top: 90px;
	bottom: 0;
	left: 0;
	right: 0px;
	
	color: black;


    visibility: hidden;
	opacity: 0;

}


.imgWrap:hover .imgDescription {
	visibility: visible;
	opacity: 1;
}
      /*
 * Globals
 */

/* Links */

a:focus,
a:hover {
  color: #fff;
}
.theme-dropdown .dropdown-menu {
  position: static;
  display: block;
  margin-bottom: 20px;
}

.theme-showcase > p > .btn {
  margin: 5px 0;
}

.theme-showcase .navbar .container {
  width: auto;
}


/* Custom default button */
.btn-default,
.btn-default:hover,
.btn-default:focus {
  color: #333;
  text-shadow: none; /* Prevent inheritence from `body` */
  background-color: #fff;
  border: 1px solid #fff;
}


/*
 * Base structure
 */

body {
  color: #fff;
  text-align: center;
  text-shadow: 0 1px 3px rgba(0,0,0,.5);
}

/* Extra markup and styles for table-esque vertical and horizontal centering */
.site-wrapper {
  display: table;
  width: 100%;
  height: 100%; /* For at least Firefox */
  min-height: 100%;
  -webkit-box-shadow: inset 0 0 100px rgba(0,0,0,.5);
          box-shadow: inset 0 0 100px rgba(0,0,0,.5);
}

.site-wrapper-inner {
  display: table-cell;
  vertical-align: top;
}
.cover-container {
  margin-right: auto;
  margin-left: auto;
}

/* Padding for spacing */
.inner {
  padding-top: 50px;
}


/*
 * Header
 */
.masthead-brand {
  margin-top: 0px;
  margin-bottom: 20px;
  margin-right: 50px
}

.masthead-nav > li {
  display: inline-block;
}
.masthead-nav > li + li {
  margin-left: 20px;
}
.masthead-nav > li > a {
  padding-right: 0;
  padding-left: 0;
  font-size: 16px;
  font-weight: bold;
  color: #fff; /* IE8 proofing */
  color: rgba(255,255,255,.75);
  border-bottom: 2px solid transparent;
}
.masthead-nav > li > a:hover,
.masthead-nav > li > a:focus {
  background-color: transparent;
  border-bottom-color: #a9a9a9;
  border-bottom-color: rgba(255,255,255,.25);
}
.masthead-nav > .active > a,
.masthead-nav > .active > a:hover,
.masthead-nav > .active > a:focus {
  color: #fff;
  border-bottom-color: #fff;
}

@media (min-width: 768px) {
  .masthead-brand {
    float: left;
  }
  .masthead-nav {
    float: right;
  }
}


/*
 * Cover
 */

.cover {
  padding: 0 20px;
}
.cover .btn-lg {
	margin-top:500px  
	
  font-weight: bold;
}


/*
 * Footer
 */

.mastfoot {
  color: #999; /* IE8 proofing */
  color: rgba(255,255,255,.5);
}


/*
 * Affix and center
 */

@media (min-width: 768px) {
  /* Pull out the header and footer */
  .masthead {
    position: fixed;
    top: 0;
  }
  .mastfoot {
    position: fixed;
    bottom: 0;
  }
  /* Start the vertical centering */
  .site-wrapper-inner {
    vertical-align: middle;
  }
  /* Handle the widths */
  .masthead,
  .mastfoot,
  .cover-container {
    width: 100%; /* Must be percentage or pixels for horizontal alignment */
  }
}

@media (min-width: 992px) {
  .masthead,
  .mastfoot,
  .cover-container {
    width: 700px;
  }
}

      body { 
        padding-top: 51px; 
      }
          .carousel-inner > .item > img, .carousel-inner > .item > a > img {
        display: block;
        height: 450px;
        min-width: 100%;
        width: 100%;
        max-width: 100%;
        line-height: 1;
    }
      
      .row { margin: 0; padding: 0 }
    </style>
</head>
<body>    
    
    <div style="color: black;text-align: left;" class="container">
        <h2>Choose one to proceed further</h2>
    </div>
    <br/>
    <div class="inner cover">
          <!--<p class="lead">
            <a href="#" class="btn btn-lg btn-default">About us</a>
          </p> -->
          <div class="col-sm-3"></div>
          <div class="col-sm-3">
            <a href="{%url 'new_student' %}" class="imgWrap"> <img class="blah grow" src="{% static 'card/images/student.png' %}" alt="Fireworks" style="width:150px;height:150px;right:50%"><p class="imgDescription">Student</p> </a>
          </div>
          <div class="col-sm-3">
            <a href="{%url 'new_employee' %}" class="imgWrap"><img class="grow" src="{% static 'card/images/faculty.png' %}" alt="Fireworks" style="width:150px;height:150px;right:50%"> <p class="imgDescription">Faculty</p> </a>
          </div>
          <div class="col-md-3"></div>
    </div>
</body>
{% endblock %}

templates/card/detail.html
{%extends 'card/base.html'%}
{% block active%}
      <li><a href="{%url 'index'%}"><i class="fas fa-home"></i>&ensp; Home</a></li>
      <li class="active"><a href="{%url 'list_student'%}"><i class="fas fa-graduation-cap"></i>&ensp; Student</a></li>
      <li><a href="{%url 'list_employee'%}"><i class="fas fa-chalkboard-teacher"></i>&ensp;Faculty</a></li>
      <li><a href="{%url 'add_new'%}"><i class="fa fa-address-card-o"></i>Register</a></li>
      <li class="dropdown ">
        <a class="dropdown-toggle " data-toggle="dropdown" href="#">Visitor
        <span class="caret"></span></a>
        <ul class="dropdown-menu ">
          <li><a href="{%url 'visitor:register'%}">Add new</a></li>
          <li><a href="{%url 'visitor:checkedin_list'%}">Checked In</a></li>
          <li><a href="{%url 'visitor:list'%}">Checked Out</a></li>
        </ul>
      </li>
    </ul>
  {% endblock active %}
{%block content%}
<head>
  <title>{{student_detail.name}}</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <style>
      .card {
 box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
 max-width: 45%;
 margin: auto;
 text-align: center;
 font-family: arial;
}

.title {
 color: grey;
 font-size: 18px;
}

/*a {
 text-decoration: none;
 font-size: 22px;
 color: black;
}*/

button:hover, a:hover {
 opacity: 0.7;
 text-decoration: none;
 color: #fff;
}


.btn-group button {
 font-size: 18px;
 background-color: #000; /* Green background */
 border: 1px solid grey; /* Green border */
 color: white; /* White text */
 padding: 10px 24px; /* Some padding */
 cursor: pointer; /* Pointer/hand icon */
 float: left; /* Float the buttons side by side */
}

/* Clear floats (clearfix hack) */
.btn-group:after {
 content: "";
 clear: both;
 display: table;
}

.btn-group button:not(:last-child) {
 border-right: none; /* Prevent double borders */
}

/* Add a background color on hover */
.btn-group button:hover {
 opacity: 0.7;
}

      
      body { 
        padding-top: 51px; 
      }
          .carousel-inner > .item > img, .carousel-inner > .item > a > img {
        display: block;
        height: 450px;
        min-width: 100%;
        width: 100%;
        max-width: 100%;
        line-height: 1;
    }
      
      .row { margin: 0; padding: 0 }
    </style>
</head>
  <div class="card" style="border-style: solid; border-color: black; border-width: 1px;border-radius: 4px;" >
    <div id="print-card">
       <img src="../media/{{MEDIA_URL}}{{student_detail.pic}}" alt="image not found" style="border-radius: 50%; margin-top: 3%; width:150px; height:150px; border-style: solid; border-color: black; border-width: 1px;" />
       <h2 style="font-family: Times New Roman;">{{student_detail.name}}</h2>
       <div class="w3-container">
         <table class="w3-table-all w3-hoverable tb1">
           <tr>
             <td>Roll Number:</td>
             <td>{{student_detail.roll_no}}</td>
           </tr>
           <tr>
             <td>Father's Name:</td>
             <td>{{student_detail.father_name}}</td>
           </tr>
           <tr>
             <td>Date Of Birth:</td>
             <td>{{student_detail.dob}}}}</td>
           </tr>
           <tr>
             <td>Programme:</td>
             <td>{{student_detail.programme}}</td>
           </tr>
           <tr>
             <td>Blood Group:</td>
             <td>{{student_detail.blood_group}}</td>
           </tr>
           <tr>
             <td>Valid Upto:</td>
             <td>{{student_detail.valid_upto}}</td>
           </tr>
           <tr>
             <td>Issued On:</td>
             <td>{{student_detail.issued_on}}</td>
           </tr>
         </table>
      </div> 
    </div>
      <div class="btn-group" style="width:100%">
         <button style="width:33.3%"><a style="display: block; color: white;" href="{% url 'update_student' student_detail.roll_no %}">Update</a></button>
         <button style="width:33.3%"><a style="display: block;color: white;" href="{% url 'delete_student' student_detail.roll_no %}">Delete</a></button>
         <button style="width:33.3%"><a style="display: block; color: white;" href="{% url 'print' student_detail.roll_no%}">Print</a></button>      
      </div>
  </div>
</body>
{% endblock %}

templates/card/list.html
{%extends 'card/base.html'%}
{% load staticfiles %}
{% block active%}
      <li><a href="{%url 'index'%}"><i class="fas fa-home"></i>&ensp; Home</a></li>
      <li class="active"><a href="{%url 'list_student'%}"><i class="fas fa-graduation-cap"></i>&ensp; Student</a></li>
      <li><a href="{%url 'list_employee'%}"><i class="fas fa-chalkboard-teacher"></i>&ensp;Faculty</a></li>
      <li><a href="{%url 'add_new'%}"><i class="fa fa-address-card-o"></i>Register</a></li>
      <li class="dropdown ">
        <a class="dropdown-toggle " data-toggle="dropdown" href="#">Visitor
        <span class="caret"></span></a>
        <ul class="dropdown-menu ">
          <li><a href="{%url 'visitor:register'%}">Add new</a></li>
          <li><a href="{%url 'visitor:checkedin_list'%}">Checked In</a></li>
          <li><a href="{%url 'visitor:list'%}">Checked Out</a></li>
        </ul>
      </li>


    </ul>
  {% endblock active %}
{%block content%}
<head>
  <title>Student List</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
  <style>
      body { 
        padding-top: 51px; 
      }
          .carousel-inner > .item > img, .carousel-inner > .item > a > img {
        display: block;
        height: 450px;
        min-width: 100%;
        width: 100%;
        max-width: 100%;
        line-height: 1;
    }
      
  .row { margin: 0; padding: 0 }
      * {
          box-sizing: border-box;
        }
      
  table {
        width:100%;
  }
      
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;

}

th, td {
  padding: 10px;
  text-align: centre;
}
table#mydata tr:nth-child(even) {
  background-color: #eee;
}
table#mydata tr:nth-child(odd) {
 background-color: #fff;
}
table#mydata th {
  opacity: 0.7;
  background-color: black;
  color: white;
}
      
    </style>
</head>
<body>
  <table class="table-bordered table table-hover" id="mydata">
        <thead>
            <tr>
                <th>Roll No.</th>
                <th>Name</th> 
                <th>Programme</th>
            </tr>
        </thead>
        
        <tbody>
          {%for s in list%}
    <tr>
      <td><a href="{% url 'detail_student' s.roll_no%}">{{s.roll_no}}</a></td>
      <td><a href="{% url 'detail_student' s.roll_no%}">{{s.name}}</a></td>
      <td><a href="{% url 'detail_student' s.roll_no%}">{{s.programme}}</a></td>
    </tr>
  {%endfor%}
  </tbody>
    </table>
    <script>
        $('#mydata').dataTable();
    </script>
    <br/>
    <br/>
</body>  
{% endblock %}